// services/constants/ApiName.js
const ApiName = {
    register: 'register',
    all_setting: 'all_setting',
    country_list: 'country_list',
    PaymentGetWayList: 'PaymentGetWayList',
    userProfileUpdate: 'userProfileUpdate',
    fetchHostProfiles: 'fetchHostProfiles',
    find_random_host: 'find_random_host',
    giftList: 'giftList',
    save_profile: 'save_profile',
    get_saved_profile: 'get_saved_profile',
    fetchBlockList: 'fetchBlockList',
    remove_from_save: 'remove_from_save',
    delete_profile: 'delete_profile',
    allSubcription: 'allSubcription',
    get_host_profile: 'get_host_profile',
    verifyPurchase: 'verifyPurchase',
    unblockHost: 'unblockHost',
    blockHost: 'blockHost',
    applyForHost: 'applyForHost',
    hostProfileUpdate: 'hostProfileUpdate',
    fcm_noti: 'fcm/send',
    getUserProfile: 'getUserProfile',
    report: 'report',
    storeFileGivePath: 'storeFileGivePath',
    diamondPlus: 'diamondPlus',
    addCoins: 'addCoins',
    diamondMinus: 'diamondMinus',
    sendNotificationToUsers: 'sendNotificationToUsers',
    sendCoin: 'sendCoin',
    fetchNotification: 'fetchNotification',
    notificationRemove: 'notificationRemove',
    generateAgoraToken: 'generateAgoraToken',
    historyAddDiamond: 'historyAddDiamond',
    historyDiamond: 'historyDiamond',
    fetchRedeemRequests: 'fetchRedeemRequests',
    placeRedeemRequest: 'placeRedeemRequest',
    verifyInAppProductPurchase: 'verifyInAppProductPurchase',
    updateUserCallStatus: 'updateUserCallStatus',
    onOff_video_call: 'onOff_video_call',
    fakeMessagesList: 'fakeMessagesList',
    reportReson: 'reportReson',
    logOut: 'logOut',
    minusCoins: 'minusCoins',
    fetchHostProfilesByGender:'fetchHostProfilesByGender'
  };
  
  export default ApiName;
  