// services/constants/ApiParams.js
const ApiParams = {
    apikey: 'apikey',
    authtoken: 'authtoken',
    country_id: 'country_id',
    user_id: 'user_id',
    dataServingType: 'data_serving_type',
    host_id: 'host_id',
    start: 'start',
    limit: 'limit',
    reason: 'reason',
    description: 'description',
    contact: 'contact',
    report_id: 'report_id',
    diamond: 'diamond',
    title: 'title',
    identity: 'identity',
    loginCode: 'login_Code',
    imagesArray: 'images[]',
    videosArray: 'video[]',
    fullName: 'fullName',
    profileimages: 'profileimages',
    username: 'username',
    email: 'email',
    loginType: 'loginType',
    deviceType: 'deviceType',
    deviceToken: 'deviceToken',
    channelName: 'channelName',
    type: 'type',
    account_info: 'account_info',
    payment_getway_title: 'payment_getway_title',
    agoraToken: 'agoraToken',
    diamond_per_min: 'diamond_per_min',
    to_user_id: 'to_user_id',
    call_status: 'call_status',
    connected_call_user_id: 'connected_call_user_id',
    my_user_id: 'my_user_id',
    is_video_call: 'is_video_call',
    one_signal_id: 'one_signal_id',
    token: 'token',
    product_id: 'product_id',
  };
  
  export default ApiParams;
  