import React from 'react'

const Terms = () => {
  return (
  <main className="text-white brightness-75 my-5 px-4 ">
    <article className="post-entry post-entry-type-page post-entry-298" itemScope="itemscope" itemType="https://schema.org/CreativeWork">
      <div className="entry-content-wrapper clearfix">
        <header className="entry-content-header" /><div className="entry-content" itemProp="text"><p>Vugo Hızlı Sohbet—Kullanıcı Sözleşmesi<br />
            Vugo Hızlı Sohbet’e hoş geldiniz! Vugo Chat uygulaması ve Vugo Chat platformunda ve web sitesinde sağlanan hizmetler, özellikler ve içerik (bu Kullanıcı Sözleşmesinde “Hizmetler” olarak adlandırıyoruz) dahil olmak üzere ürünlerimizi kullanmak üzere kaydolduğunuz için teşekkür ederiz. “Siz” veya “kullanıcı” terimleri, Hizmetlerimize erişen veya Hizmetlerimizi başka bir şekilde kullanan kişi veya kuruluşu ifade eder.​</p>
          <p>Bu yazılımın çalışma düzenini standartlaştırmak, tüm tarafların hak ve yükümlülüklerini netleştirmek ve tüm tarafların meşru hak ve çıkarlarını korumak amacıyla bu sözleşme özel olarak hazırlanmıştır. Bu yazılımın kullanıcısı olarak kaydolmadan önce işbu “Kullanıcı Sözleşmesini” (bundan böyle “Sözleşme” olarak anılacaktır) dikkatlice okumanızı hatırlatırız.</p>
          <p>Bu Sözleşmede kalın harflerle gösterilen ve altı çizili içerik özellikle dikkatinize sunulmuştur. Lütfen bu Sözleşmenin şartlarını tam olarak anladığınızdan emin olun ve bu Sözleşmeyi kabul etmeyi veya kabul etmemeyi seçin. Bu Sözleşmenin tüm şartlarını kabul etmediğiniz sürece kayıt olma, oturum açma veya bu Sözleşme kapsamındaki hizmetleri kullanma hakkınız yoktur. Kayıt olmanız, oturum açmanız, kullanmanız vb. bu Sözleşmeyi kabul ettiğiniz ve bu Sözleşmenin şartlarına tabi olmayı kabul ettiğiniz anlamına gelecektir.</p>
          <p>Şirketin bu Sözleşmeyi ve ek sözleşmelerini ve ayrıca platformdaki normatif şartları değiştirme hakkının olması durumunda, bu Sözleşme Şirket tarafından herhangi bir zamanda güncellenebilir. Güncellenen sözleşme şartları açıklandıktan sonra orijinal içerik önceden haber verilmeksizin değiştirilecektir. Güncellenen sözleşme koşullarını bu yazılımda görüntüleyebilirsiniz. Şirketimiz sözleşmenin şartlarını değiştirdikten sonra, değiştirilen şartları kabul etmemeniz durumunda, lütfen bu yazılımı kullanmayı derhal bırakın. Bu yazılımın sağladığı hizmetleri kullanmaya devam etmeniz, değiştirilen sözleşmeyi kabul ettiğiniz anlamına gelecektir.​</p>
          <p>Bu hizmet 18 yaşın altındaki kullanıcılara yönelik değildir. 18 yaşın altındaysanız, Hizmetleri hiçbir zaman ve hiçbir şekilde kullanamaz veya Hizmetlere erişemezsiniz. 18 yaşın üzerinde olduğunuzu veya ebeveyninizin veya yasal vasinizin (18 yaş üstü) Hizmeti kullanmanız için size yetki verdiğini ve bu Koşulları sizin adınıza imzaladığını doğrulamanız gerekir.</p>
          <p>Bu Sözleşmenin şartlarına uyacak ve Yazılımı doğru ve doğru bir şekilde kullanacaksınız. Bu Sözleşmenin herhangi bir hükmünü ihlal etmeniz, fiili veya olası sorunlara veya yükümlülüklere, gecikmiş hizmet ücretleri, üçüncü tarafların fikri mülkiyet haklarının ihlaline veya dolandırıcılık/ahlaksızlık veya yasa dışı faaliyetlerde bulunmanız durumunda, bu yazılımın size sağlanan hizmeti kesintiye uğratma veya sonlandırma hakkı vardır. Hizmette yayınladığınız her türlü içeriği veya bilgiyi kaldırın ve Yazılıma veya Hizmetlere (veya Hizmetlerin herhangi bir kısmına veya özelliğine) erişiminizi veya bunları kullanmanızı yasaklayın. Gerekirse sorumlu tutulacaksınız.</p>
          <p>1. Hesap<br />
            a) Hizmetlerimizi kullanabilmeniz için sizden bir hesap oluşturmanızı isteyebilir veya size bir hesap atayabiliriz. Size önceden bildirimde bulunmadan hesap kayıt yönteminizi değiştirebilir, gerektiğinde giriş yapabilir ve ürün ihtiyaçlarına göre hesap kaydı, bağlama, kayıt vb. değişiklikler yapabiliriz.​</p>
          <p>b) Bir yazılım hesabını başarıyla kaydettikten sonra, şirketin diğer ürün yazılımları için de sizin adınıza hesap açması konusunda şirkete yetki vereceğinizi kabul edersiniz. Diğer spesifik ürün yazılımları şirketin fiili çalışma koşullarına bağlıdır.</p>
          <p>c) Yazılım hesabının mülkiyeti şirketimize aittir. Kayıt işlemini tamamladıktan sonra yazılım hesabını kullanma hakkını elde edeceksiniz. Kullanım hakkı yalnızca ilk kayıt yaptırana aittir ve hediye edilmesi, ödünç alınması, kiralanması, devredilmesi veya satılması yasaktır.​</p>
          <p>d) Hesabınızın güvenliğinin sağlanmasından siz sorumlusunuz. Hesabınızın yanlış kullanımınız nedeniyle kullanılması veya şifrenizin çalınması durumunda, hesabınızda gerçekleştirdiğiniz tüm işlemlerin sorumluluğu size ait kabul edilir ve başkalarının hesabınızı kullanarak yaptığı tüm işlemlerin sorumluluğunu üstlenmeniz gerekir. hesap. Hesabınızın veya hesap şifrenizin izinsiz kullanıldığından şüpheleniyorsanız veya bunun farkına varırsanız, lütfen bize hemen bildirin.​</p>
          <p>e) Hiçbir durumda başka bir kullanıcının hesabını veya şifresini kullanmamayı kabul edersiniz.​</p>
          <p>2. Hizmet içeriği<br />
            a) Sanal hediyeler satın almanıza veya göndermenize izin vermek dahil ancak bunlarla sınırlı olmamak üzere, gerçek koşullara dayalı olarak bu yazılımın belirli hizmetlerini sağlamak. Sağlanan hizmetleri, tamamen kendi takdirimize bağlı olarak, size önceden bildirimde bulunmaksızın herhangi bir zamanda değiştirebiliriz.</p>
          <p>b) Size e-posta, müşteriler, anlık mesajlar, kısa mesajlar, web sayfaları veya diğer yasal yollarla ticari amaçlarla promosyon veya diğer ilgili ticari bilgileri ve bildirimleri gönderme hakkımız olduğunu anlıyor ve kabul ediyorsunuz. Cep telefonu ağlarının benzersiz doğası nedeniyle cep telefonu bilgilerinize erişebiliyoruz.</p>
          <p>3. Kullanıcı bilgilerinin korunması<br />
            a) Hesap açma veya bu hizmeti kullanma sürecinde kanun, yönetmelik ve normatif belgelerin (bundan böyle “kanun ve yönetmelikler” olarak anılacaktır) gerektirdiği kimlik bilgileri gibi bazı gerekli bilgileri doldurmanız veya göndermeniz gerekebilir. . Gönderdiğiniz bilgilerin eksik olması veya yasa ve yönetmeliklere uygun olmaması durumunda, bu yazılımı kullanamayabilir veya bu yazılımı kullanma sürecinde kısıtlanabilirsiniz.</p>
          <p>b) Kullanıcı bilgileri, özel bilgileri ve özel olmayan bilgileri içerir. Özel bilgiler, gerçek adınız, kimlik numaranız, cep telefonu numaranız vb. gibi kullanıcıyı tanımlayabilecek veya kişisel iletişimleri içeren bilgileri ifade eder; özel olmayan bilgiler, açık ve objektif bilgiler olan hizmet çalışma durumunuzu ve alışkanlıklarınızı ifade eder; bu kayıtta yansıtılan diğer genel bilgilerin kişisel gizliliğini içermeyen sunucu tarafı temel yazılımında, kişisel gizlilik bilgilerinin açıklanmasını kabul etmiş olursunuz.</p>
          <p>c) Bu yazılımın teknolojisini ve hizmetlerini işletmek ve geliştirmek, size daha iyi bir kullanıcı deneyimi sunmak ve hizmet kalitesini artırmak amacıyla Şirket, kullanıcıya ilişkin kullanıcı bilgilerini toplayabilir, kullanabilir veya üçüncü kişilere verebilir. Ayrıntılar için lütfen bunu dikkatlice okuyun. Yazılımın “Gizlilik Politikası”.</p>
          <p>d) Bu yazılımın sunduğu hizmetler coğrafi konuma dayalı mobil sosyal hizmetler olduğundan, coğrafi konum bilgileriniz gizli olmayan bilgilerdir. Bu yazılım hesabına başarılı bir şekilde kaydolmanız, yazılımın çıkarma, ifşa etme ve kullanma yetkisinin teyidi olarak kabul edilir. coğrafi konumunuz. Coğrafi konum bilgileriniz kamuya açık bilgilerinizden biri olarak kullanılacak ve bu yazılım tarafından diğer kullanıcılara açıklanacaktır. Coğrafi konum bilgilerini diğer kullanıcılara açıklamayı bırakmanız gerekiyorsa yetkilendirme bilgilerini kendiniz değiştirebilirsiniz.</p>
          <p>4. Yetkilendirme<br />
            a) Bu yazılımdaki bazı hizmetlerden yalnızca yazılımın coğrafi konumunuzu kullanmasına izin vermenizin ardından yararlanabilirsiniz. Hizmetlerimizin belirli özelliklerini kullanabilmek için GPS konumunuzu bize sağlamalı ve yetkilendirmelisiniz. Coğrafi konum bilgilerini sağlamayı bırakmanız gerekiyorsa coğrafi konum yetkilendirmesini kendiniz kapatabilirsiniz.</p>
          <p>b) Hizmetlerimizden daha fazla yararlanabilmeniz için, cihazınızdaki adres defterini, kişi listesini ve benzersiz telefon tanımlayıcıyı (IMEI, UDID veya diğer) toplayıp kullanması için şirketimize yetki vermeniz gerekir.</p>
          <p>c) Sunucularımızın, hizmetlerimizi iyileştirmek ve geliştirmek amacıyla düzenli olarak günlük bilgileri topladığını kabul edersiniz.</p>
          <p>d) Fikri mülkiyet haklarıyla korunan içeriği (fotoğraflar gibi) yayınladığınızda veya yüklediğinizde, bize telifsiz, devredilebilir, alt lisanslanabilir, barındırma, kullanım, dağıtım, uyarlama, değişiklik, çoğaltma, kamuya açık teşhir, yayınlama, Çeviri hakkı vermiş olursunuz. yüklediğiniz içerik ve bunlardan türetilen çalışmalar. Ayrıca diğer üçüncü taraflara içeriğinizi ve bundan türetilmiş çalışmalarınızı görüntüleme, erişme, kullanma, indirme, uyarlama, değiştirme ve kopyalama yetkisi verebiliriz.</p>
          <p>5. İçerik özellikleri<br />
            a) Bu sözleşmenin tanımladığı şey, kayıt bilgileri ve hesap avatarı, ad, kişisel açıklama, ders kitapları, ses, resimler, videolar gibi kişisel ayrıntılar dahil ancak bunlarla sınırlı olmamak üzere herhangi bir içeriği oluşturmanız, yüklemeniz, kopyalamanız, yayınlamanız ve dağıtmanızdır. gönderilen resimler, yanıtlar veya otomatik yanıt mesajları ve ilgili bağlantı sayfaları ve yazılımı kullanırken oluşturulan diğer içerikler.</p>
          <p>b) Herhangi bir Kullanıcı İçeriğinin doğruluğunu, eksiksizliğini, uygunluğunu veya kalitesini garanti etmiyoruz ve hiçbir durumda Kullanıcı İçeriğinden sorumlu olmayacağız. Yazılım içinde veya Yazılım aracılığıyla ilettiğiniz veya yayınladığınız hiçbir şey Yazılımın/Şirketin görüşlerini, pozisyonlarını veya politikalarını yansıtmaz veya temsil etmez ve bunları yansıttığı veya temsil ettiği varsayılmamalıdır.</p>
          <p>c) Bu yazılım tarafından iletilen bilgilerin gerçekliği, yasallığı, zararsızlığı, doğruluğu ve geçerliliğinden yalnızca siz sorumlusunuz ve yaptığınız, yüklediğiniz, kopyaladığınız, yayınladığınız ve yaydığınız bilgi ve eylemlerle ilgili her türlü hukuki sonuçtan siz sorumlusunuz. Yazılım değil, risk size aittir. Yazılıma veya üçüncü bir tarafa zarar verilmesi halinde, kanuna uygun olarak tarafınıza tazminat ödenecektir ve şirket, işbu sözleşme uyarınca hukuki sorumluluğunuzu takip etme hakkına sahiptir.</p>
          <p>d) Bu yazılımı aşağıdaki eylemleri oluşturmak, yüklemek, kopyalamak, göndermek veya daha azını yapmak için kullanmanıza izin verilmez. Bu yazılımı aşağıdaki içeriği oluşturmak, aktarmak, kopyalamak, yayınlamak veya iletmek için kullanırsanız, silme hakkımız vardır. Gönderdiğiniz içerik ciddiyse, hesabı askıya alacağız ve gerekirse yasal sorumluluk üstleneceğiz:</p>
          <p>1. Ülkenin dini politikalarını baltalamak, tarikatları ve feodal hurafeleri teşvik etmek;<br />
            2. Dedikodu yaymak, toplumsal düzeni bozmak, toplumsal istikrarı bozmak;<br />
            3. Her türlü cinsel veya cinsel açıdan müstehcen içerik de dahil olmak üzere müstehcen veya pornografik içerik yaymak;<br />
            4. Kumar, şiddet, cinayet, terör veya suça azmettirme;<br />
            5. Başkalarına hakaret etmek veya iftira atmak, başkalarının meşru hak ve çıkarlarını ihlal etmek veya başkalarını dolandırmak;<br />
            6. İstismar, korkutma veya tehdit içeren içerikler;<br />
            7. Taciz, spam, kötü amaçlı bilgiler veya aldatıcı bilgiler içeren;<br />
            8. Başkalarının mahremiyetini, kişisel bilgilerini veya verilerini ifşa etmeyin veya bunlara dahil etmeyin;<br />
            9. Başkalarının itibar haklarını, portre haklarını, fikri mülkiyet haklarını, ticari sırlarını, patentlerini, ticari markalarını ve diğer meşru hak ve menfaatlerini ihlal etmek;<br />
            10. Reşit olmayanların çıkarlarını herhangi bir şekilde tehlikeye atmak;<br />
            11. Diğer kullanıcıları başka şekillerde takip etmek veya taciz etmek;<br />
            12. Yanlış bilgi göndermek veya yayınlamak ya da başkalarının portrelerini veya bilgilerini çalmak, başka kişilerin adlarını taklit etmek veya kullanmak;<br />
            13. Diğer kullanıcıları bağlantılı sayfaları takip etmeye, tıklamaya veya bilgi paylaşmaya zorlamak veya teşvik etmek;<br />
            14. Gerçekleri uydurmak, gerçeği gizlemek, başkalarını yanıltmak ve aldatmak;<br />
            15. Mağaza ürünlerinin, etkinliklerinin, fiyatlarının, adres ve iletişim bilgilerinin kişisel tanıtımı, üye alımı, personel alımı, yarı zamanlı iş ilanı vb. dahil ancak bunlarla sınırlı olmamak üzere tanıtım ve satış reklamına dayalı faaliyetlerde bulunmak yasaktır. .<br />
            16. Toplu olarak sahte hesaplar oluşturmak için teknik araçları kullanın;<br />
            17. Kamu düzenini ve iyi gelenekleri ihlal eden veya rahatsız edici veya rahatsız edici bilgi veya içerik içeren;<br />
            18. Yasaların, yönetmeliklerin ve diğer normatif belge ve politikaların (konumunuz, hesap kayıt yeriniz, yazılımın çalıştırıldığı konum, içeriğin görüntülenebileceği konum vb., yasalar, düzenlemeler ve diğer normatif belge ve politikalar dahil) diğer ihlalleri, diğer ihlaller Üçüncü tarafların meşru hakları ve çıkarları, yazılımın normal çalışmasına müdahale eden veya yazılım tarafından açıkça yetkilendirilmeyen eylemlerdir.<br />
            6. Sınırlayıcı faktörler<br />
            a) Aşağıdaki durumları ihlal etmeniz ve yazılıma veya üçüncü bir kişiye zarar vermeniz durumunda, kanuna göre tazminat ödeyeceksiniz ve şirketin, işbu sözleşme uyarınca sözleşmenin ihlali nedeniyle sorumluluğunuzu takip etme hakkı bulunmaktadır. Kanun ve yönetmeliklere uygun olarak yasa dışı, sözleşme ihlali veya ihlalinize karşı her türlü iyileştirici önlemi alma, uygun hukuki işlemleri yapma ve ilgili bilgileri yetkili makamlara açıklama hakkına sahibiz.</p>
          <p>1. Bu yazılımı veya herhangi bir hizmeti kopyalayamaz, değiştiremez, uyarlayamaz, herhangi bir dile çeviremez, dağıtamaz veya bunlara dayalı türev çalışmalar oluşturamazsınız;<br />
            2. Lütfen yazılım veya herhangi bir hizmetteki veya bunlarla ilgili hiçbir telif hakkını veya diğer mülkiyet bildirimlerini silmeyin, gizlemeyin veya değiştirmeyin;<br />
            3. Şirketin fikri mülkiyet haklarına sahip olduğu içerikleri kullanmanıza, kiralamanıza, ödünç vermenize, kopyalamanıza, değiştirmenize, bağlantı vermenize, yeniden basmanıza, derlemenize, yayınlamanıza, yayımlamanıza, yansıtma siteleri kurmanıza vb. izin verilmez;<br />
            4. Lütfen ürünlerimizi veya hizmetlerimizi solucan, virüs veya herhangi bir yıkıcı kodu yaymak için kullanmayın.<br />
            5. Şirketimiz tarafından geliştirilmeyen veya yetkilendirilmeyen üçüncü taraf yazılımlar, eklentiler veya sistemler aracılığıyla oturum açmanıza veya yazılım ve hizmetleri kullanmanıza veya üçüncü taraf yazılım veya eklentileri üretmenize, yayınlamanıza veya dağıtmanıza izin verilmez. ins – şirketimiz ve sistemlerimiz tarafından geliştirilmeyen veya yetkilendirilmeyen eklentiler veya eklentiler;<br />
            6. Yazılımın işleyişindeki talimatları ve verileri değiştiremez veya taklit edemez, yazılımın işlevlerini veya çalışma etkilerini ekleyemez, silemez veya değiştiremezsiniz ve yukarıdaki amaçlar için kullanılan yazılım ve yöntemleri çalıştıramaz veya kamuya yayamazsınız. Bu eylemlerin ticari amaçlı olup olmadığına bakılmaksızın;<br />
            7. Lütfen yazılıma ters mühendislik yapmayın, ters derlemeyin, kaynak koda dönüştürmeyin veya yazılımın kaynak kodunu başka yollarla keşfetmeye çalışmayın;<br />
            8. Lütfen bu yazılımı veya bu yazılımın çalışması sırasında herhangi bir terminal belleğine gönderilen verileri, bu yazılımın çalışması sırasında istemci ile sunucu arasındaki etkileşim verilerini ve verileri kopyalamayın, değiştirmeyin, eklemeyin, silmeyin veya bağlamayın. Sistem yazılımının çalışması için gereklidir. Yazılıma ve ilgili sistemlere erişim için Şirket tarafından yetkilendirilmeyen eklentileri, eklentileri veya üçüncü taraf araçlarını/hizmetlerini kullanmak dahil ancak bunlarla sınırlı olmamak üzere herhangi bir türev çalışma yürütmek veya oluşturmak;<br />
            9. Önceden yazılı iznimiz olmadan kullanıcı adınızda bir alan adı veya URL kullanamazsınız.<br />
            7. Yeni sürüm<br />
            a) Yazılım veya Hizmetlerde değişiklik yapma veya ek işlevler ekleme ya da kendi takdirimize bağlı olarak programlama düzeltmeleri, güncellemeler ve yükseltmeler sağlama hakkını saklı tutarız. Yazılımın veya herhangi bir Hizmetin başka herhangi bir işlevselliğini veya özelliğini veya herhangi bir değişikliği, güncellemeyi, desteği, bakımı veya sonraki sürümleri kullanımınıza sunma yükümlülüğümüz yoktur. Yazılımın herhangi bir ek işlevini veya özelliğini, herhangi bir değişikliği, güncellemeyi veya yeni sürümü indirmek, yüklemek veya kullanmak istiyorsanız, güncellenmiş sürümdeki Kullanım Koşullarını kabul etmeniz gerekebilir.</p>
          <p>b) Yazılımın diğer işlevlerini veya özelliklerini ya da değiştirilmiş, güncellenmiş veya yükseltilmiş sürümlerini otomatik olarak yayınlayabileceğimizi ve dolayısıyla kullandığınız veya cihazınıza yüklediğiniz Yazılımın sürümünü değiştirebileceğimizi, güncelleyebileceğimizi veya yükseltebileceğimizi kabul edersiniz.</p>
          <p>c) Cihazınızın bu tür değişiklikleri, yükseltmeleri veya güncellemeleri otomatik olarak talep edebileceğini ve/veya otomatik olarak alabileceğini kabul edersiniz.</p>
          <p>8. Sanal para birimi<br />
            a) Elmas isimli “sanal ürünler” satın alabilir ve kullanabilirsiniz (sanal ürünlerin adının değiştirilmesi bu sözleşmenin geçerliliğini etkilemeyecektir). Aksi belirtilmediği sürece Sanal Öğeler yalnızca Yazılım içerisinde kullanılabilir ve Yazılımın dışındaki programlarda satın alma gücü yoktur.</p>
          <p>b) Sanal eşyalarınızı izin verdiğimiz kanallar üzerinden şarj edebilirsiniz. Döviz kurunu zaman zaman yazılım arayüzümüzde göstermeden değiştirme hakkını saklı tutuyoruz. Çeşitli faktörlere dayalı olarak zaman zaman sanal öğeler ve diğer işlemlerle ilgili kurallar oluşturma veya değiştirme hakkını saklı tutuyoruz.</p>
          <p>c) Lütfen yeniden yüklemeden önce hesabınızı dikkatlice kontrol edin. Hesap girişi hatalarından, operasyonel hatalardan vb. kaynaklanan tüm kayıplar sizin sorumluluğunuzdadır ve kayıplarınız için size tazminat ödemeyeceğiz.</p>
          <p>d) Sanal öğeler, hediyeler gibi katma değerli yazılım hizmetlerinin satın alınmasında kullanılabilir. Spesifik fiyatlandırma bilgileri, döviz kurları ve kullanım politikaları tarafımızdan belirlenecek ve hizmet arayüzümüze bağlı olacaktır.</p>
          <p>e) Aksi belirtilmedikçe sanal eşyalar, yazılım platformu dışında üçüncü kişilerle veya üçüncü taraf platformlarda sanal eşya ticareti yapılamaması da dahil olmak üzere başka herhangi bir amaçla kullanılamaz.</p>
          <p>f) Yasadışı veya yetkisiz kanallar aracılığıyla para yatırma işlemi yapılmamasını sağlamalısınız. Kuralları ihlal ederseniz ve sanal öğeler satın almak için yasal olmayan bir şekilde yükleme yaparsanız, yüklemenin başarılı olacağını veya tamamlanacağını garanti etmiyoruz. Bu davranışın haklarınıza zarar vermesi durumunda zararınızı tazmin etmeyeceğiz. Ayrıca bu Sözleşmeyi feshetme veya hesabınızı sınırlandırma ve sizden olan borçları takip etme hakkımızı da saklı tutuyoruz.</p>
          <p>g) Yukarıdaki gereklilikleri ihlal etmeniz durumunda, sizin veya üçüncü tarafların neden olduğu hiçbir kayıptan sorumlu olmayacağız ve hesabınızın veya kullanım davranışınızın hileli veya anormal olduğundan şüphelenmemiz durumunda, sanal öğeleri kullanmanızı, belirtilen süre bitene kadar reddedeceğiz. ilgili Bu Anlaşmanın hükümleri yasaklayıcı tedbirler almaktadır.</p>
          <p>h) Yasalarda aksi belirtilmedikçe, Hizmet aracılığıyla satın alınan tüm sanal öğeler hiçbir durumda iade edilemez ve devredilemez. Satın aldığınız herhangi bir hizmet veya ürüne ilişkin Sanal Öğeleri başka bir hizmet veya ürüne iade edemez veya devredemezsiniz.</p>
          <p>i) Reşit olmayanların sanal para birimi hizmetlerini kullanmasını teşvik etmiyoruz. Reşit değilseniz, sanal para birimini bir vasinin gözetiminde tutmanız gerekir.</p>
          <p>j) Aşağıdaki nedenlerden dolayı sanal para birimini veya sanal ürün ve hizmetleri sağlayamamamızdan kaynaklanan zararlardan siz sorumlu olacaksınız:</p>
          <p>1. Hesap bilgilerinizi unuttunuz<br />
            2. Kullanıcı sözleşmesinin ihlali nedeniyle hesabınızın dondurulması;<br />
            3. Şifrenizi başkalarına açıklıyorsunuz;<br />
            4. Ödeme kanalı kurumunun ihmali nedeniyle;<br />
            5. Diğer kullanıcıların kasıtlı veya ağır ihmalinden veya yasa ve yönetmelikleri ihlal etmesinden kaynaklanan;<br />
            6. Sizden kaynaklanan diğer sebepler;<br />
            k) Aşağıdaki durumlarda sanal para birimi kullanma hakkınızı sınırlayabiliriz:</p>
          <p>1. Sanal para yükleme işleminin banka, ödeme kanalı veya mahkeme tarafından geçersiz sayılması;<br />
            2. Yeniden yükleme için kullanılan fonlar yasadışı veya uygunsuz gelir olarak kabul edilir ve mahkeme veya diğer kurumlar bunları iade etmemizi talep eder;<br />
            3. Kullanıcı bir geri ödeme veya para iadesi başlatır ancak “geri ödeme sonucu” bankanın, ödeme ağ geçidinin, mahkemenin, tahkim mahkemesinin veya bizim kararımıza bağlıdır;<br />
            4. Sanal paranın iade veya iade edilmesine neden olan diğer durumlar.<br />
            9. Üye Hizmetleri<br />
            1. Üyelik hizmetlerini satın alabilirsiniz. Dahil olan hizmet içeriği ve fiyat bilgileri, bu hizmetin ilgili sayfalarında görüntülenen bilgilere tabidir.<br />
            2. Üyelik hizmetlerinin ücretlendirme standartlarını ve içeriğini istediğimiz zaman ayarlayabiliriz.<br />
            3. Kanun ve yönetmeliklerde açıkça belirtilmediği sürece, ödeme başarılı olduktan sonra hiçbir koşulda transfere veya para iadesine izin verilmez.<br />
            4. Ödeme hizmetinde belirtilen geçerlilik süresi içerisinde hizmetimizi kullanmadığınız takdirde, abonelik sona erdikten sonra hizmet otomatik olarak sonlandırılacak olup, hizmet kesintiye uğramayacak ve uzatılmayacaktır.<br />
            5. Üye olurken göndereceğiniz içerik ve kişisel bilgilerin doğru ve geçerli olması gerekmektedir.<br />
            6. Kayıtlı kişisel bilgilerinizi gerektiğinde değiştirmelisiniz, aksi takdirde üyeliğinizi tam ve etkin bir şekilde kullanamamanın sonuçlarına katlanacaksınız.<br />
            10. Bilgi depolama<br />
            Bu Kullanım Koşullarına tabi olarak, içeriğinizi (varsa) saklamak için makul çabayı göstereceğiz ve herhangi bir içeriğin (depolanan içerik dahil) kaybından, silinmesinden veya zarar görmesinden sorumlu olmadığımızı kabul ve beyan edersiniz. hiçbir sorumluluğumuz yoktur ve herhangi bir İçeriği koruma, erişim sağlama veya iade etme yükümlülüğümüz yoktur.</p>
          <p>11. Veri maliyetleri<br />
            Hizmetleri kullanırken, Hizmetlerin ve/veya Hizmetlerin yeni sürümlerini kullanmaya veya güncellemeye veya yükseltmeye ilişkin veri ücretleri de dahil olmak üzere kendi mobil ücretlerinizi ödemek sizin sorumluluğunuzdadır. Bu ücretlerin ne olduğundan emin değilseniz hizmeti kullanmadan önce veri sağlayıcınıza danışın.</p>
          <p>12. Üçüncü taraf ürün ve hizmetler<br />
            1. Bu yazılımın sağladığı hizmetler reklamlara dahil edilebilir. Bu yazılımı kullanırken, bu yazılımın sağladığı reklam verenler ve ortaklar tarafından sağlanan hizmetleri ve üçüncü şahısları göstermeyi kabul edersiniz. Yasa ve yönetmeliklerde açıkça belirtilmediği sürece, reklam bilgilerinin işlenmesinden siz sorumlusunuz. Yukarıda adı geçen reklamverenlerin sağladığı reklam bilgileri veya içerikleriyle uğraşmanız sonucunda maruz kalabileceğiniz herhangi bir kayıp veya zarardan Şirket’in hiçbir sorumluluğu yoktur. hiçbir sorumluluk kabul etmeyin.<br />
            2. Bu yazılımda üçüncü kişiler tarafından sağlanan ürün ve hizmetleri kullandığınızda, bu sözleşme hükümlerine uymanın yanı sıra, üçüncü kişilerin kullanıcı sözleşmesine de uymanız gerekmektedir. Şirket, üçüncü taraflarca sağlanan hizmet ve ürünlerin güvenliğini, doğruluğunu ve etkililiğini ve ayrıca üçüncü taraf hizmet ve ürünlerinin neden olduğu, üçüncü taraf hizmet ve ürünlerinin neden olduğu ihtilaflar ve hasarlar gibi diğer belirsiz riskleri garanti etmez. Şirket ve Şirket hiçbir sorumluluk kabul etmeyecektir.<br />
            13. Acil servislerden yararlanamama<br />
            Yazılım ve Hizmetler, herhangi bir türdeki hastaneyi veya emniyet teşkilatını destekleme veya barındırma amacı taşımaz. Şirketimizin yürürlükteki herhangi bir yerel ve/veya ulusal kural, düzenleme veya yasa uyarınca acil durum hizmetleri sağlamasına gerek olmadığını kabul ve beyan edersiniz.</p>
          <p>14. Yetkisiz kullanıma karşı koruyun.<br />
            Şirketimiz, teknik engeller ve IP haritalama dahil ancak bunlarla sınırlı olmamak üzere, yazılım veya hizmetlerin izinsiz kullanımını önlemek için gerekli görülen her türlü yasal yola başvurma hakkını saklı tutar.</p>
          <p>15. Garanti yok<br />
            Vugo, herhangi bir hizmette görüntülenen veya iletilen içeriğin kesintisiz, hatalardan, virüslerden veya diğer zararlı bileşenlerden arınmış olacağını garanti etmez ve Vugo, yukarıdaki içeriklerin herhangi birinin düzeltileceğini garanti etmez.</p>
          <p>16. Başlık<br />
            Buradaki başlık referansları yalnızca kolaylık sağlamak içindir, bu Kullanım Koşullarının bir parçasını oluşturmaz ve buradaki herhangi bir hükmü sınırladığı veya etkilediği düşünülmez.</p>
          <p>17. Gizlilik Politikası<br />
            Gizlilik politikamızın en son sürümünü Vugo ayarlar sayfasında ve kayıt sayfasında bulabilirsiniz.</p>
          <p>18. Sözleşmeye bağlı kapasite<br />
            Bu Kullanıcı Sözleşmesinde belirtilen şartları tam olarak okuyabildiğinizi ve bunlara girebileceğinizi ve bu Kullanıcı Sözleşmesinin şart ve koşullarına uyacağınızı kabul edersiniz.</p>
          <p>Bu Kullanıcı Sözleşmesiyle ilgili herhangi bir sorunuz varsa lütfen bizimle e-posta yoluyla iletişime geçin</p>
        </div><footer className="entry-footer" />			</div>
    </article>{/*end post-entry*/}
    {/*end content*/}
  </main>
  )
}

export default Terms